### ISSUE TITLE
Missing fd_normal

### ISSUE THREAD

**Issue by goyalpike** [rmojgani/PhysicsAwareAE#1]
Dear Rambod,

Thank you for providing the codes. I was running the code ```main_opt_config03``` for 2DRiemann, but unfortunately, I get the following error:

```
The code is initiated on Serial 
ssssssssssssssssssssssssssssssssssssssssssssss
Unrecognized function or variable 'fd_normal'.

Error in main (line 48)
Dx = sparse(fd_normal(Nx,order_D1,x,1));

Error in main_opt (line 10)
main

Error in main_opt_config03 (line 32)
main_opt
````

Can you please help me with this? I am running the code on Matlab2020b. 

Thank you in advance!

Best,
Pawan

**Comment by rmojgani** [comment]
Hi,
Thanks for bringing this up, the function is defined here 

https://github.com/rmojgani/PhysicsAwareAE/blob/f45f768b9c97f33bea03532d83264fbfbc29e945/Experiments/rotatedA/fd_normal.m

I'm not sure why the path is not added as you run the code, probably I have to reorganize some of the files. Meanwhile, add the path to the file, or copy the file to the same folder as `main_opt`

**Comment by rmojgani** [comment]
@goyalpike 
All missing files added to the util directory. 
It should resolve the issues, let me know otherwise
